[package]
name = "storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
#mcdb_map = []
compress_type = []

[dependencies]
skiplist = "0.5.1"
